# Generated by Django 5.2.8 on 2025-11-18 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_librarybook_event_exam_fee_leaveapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Meeting title', max_length=200)),
                ('meeting_type', models.CharField(choices=[('staff', 'Staff Meeting'), ('parent', 'Parent Meeting'), ('student', 'Student Meeting'), ('general', 'General Meeting')], max_length=20)),
                ('description', models.TextField(help_text='Meeting agenda and details')),
                ('topic', models.CharField(help_text='Main discussion topic', max_length=300)),
                ('meeting_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(help_text='Meeting venue', max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_virtual', models.BooleanField(default=False, help_text='Is this an online meeting?')),
                ('meeting_link', models.URLField(blank=True, help_text='Online meeting link (Zoom, Google Meet, etc.)', null=True)),
                ('meeting_notes', models.TextField(blank=True, help_text='Meeting minutes and notes', null=True)),
                ('action_items', models.TextField(blank=True, help_text='Action items and decisions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organized_by', models.ForeignKey(help_text='Principal or admin organizing the meeting', on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, help_text='Users invited to the meeting', related_name='meetings_attending', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-meeting_date', '-start_time'],
            },
        ),
    ]
